#!/usr/bin/ruby

require 'pp'
require 'json'
require './cpu.rb'

def signed_rand max
  rand(2 * max - 1) - max + 1
end

def random_instruction
  case INSTRUCTIONS.sample
  when LOAD then [LOAD, rand(2),       rand(NUM_REG)]
  when ADD  then [ADD,  rand(NUM_REG), rand(NUM_REG)]
  when MUL  then [MUL,  rand(NUM_REG), rand(NUM_REG)]
  when NEG  then [NEG,  rand(NUM_REG)]
  # when JMP  then [JMP,  signed_rand(10)]
  when RET  then [RET,  rand(NUM_REG)]
  end
end

def random_program length
  Array.new(length) {random_instruction}
end

def mutate_program prog
  10.times {
    case rand 10
    when 0 then prog.delete_at rand(prog.size)
    when 1, 2, 3 then prog.insert rand(prog.size + 1), random_instruction
    when 4...10
      instr = prog.sample
      next unless instr
      case instr[0]
      when LOAD
        case rand 2
        when 0 then instr[1] += signed_rand 5
        when 1 then instr[2] = rand(NUM_REG)
        end
      when ADD, MUL
        case rand 2
        when 0 then instr[1] = rand(NUM_REG)
        when 1 then instr[2] = rand(NUM_REG)
        end
      when NEG, RET
        instr[1] = rand(NUM_REG)
      # when JMP
      #   instr[1] += signed_rand 5
      end
    end
  }
end

def run_evolution num_generations,
                  population_size,
                  children_per_parent,
                  generate_individual,
                  mutate_individual,
                  score_individual
  population = Array.new(population_size) {
    individual = generate_individual.call
    score = score_individual.call individual
    [score, individual]
  }.sort_by {|x| x[0]}
  num_generations.times {
    return population[0][1] if population[0][0] == 0
    children = population.flat_map {|parent_score, parent|
      Array.new(children_per_parent) {
        child = mutate_individual.call parent
        child_score = score_individual.call child
        [child_score, child]
      }
    }
    population = (population + children).sort_by {|x| x[0]}[0...population_size]
  }
  nil
end

def goal n
  5 * n
end

solution = run_evolution 1000,
                         10,
                         3,
                         lambda {random_program 5},
                         lambda {|prog|
  copy = prog.map(&:dup)
  mutate_program copy
  copy
},
                         lambda {|prog|
  10.times.map {|n|
    result = run_program(prog, n, 30)
    result ? (goal(n) - result).abs : 9999999999
  }.reduce(&:+)
}

if solution
  json = JSON.generate(solution).gsub("],", "],\n ")
  puts json
  File.write 'last-solution', json
else
  puts "Failed"
end
